### ISSUE TITLE
Read me: rosrun osrf_gear gear.py -f 'catkin_find --share osrf_gear'/config/qual1a.yaml '~/catkin_ws/src/ariac_qual_1/config/qual_1_conf.yaml 

### ISSUE THREAD

**Issue by AhmedElsiddieg** [cdrwolfe/ariac_qual_1#1]
instead:
 ```rosrun osrf_gear gear.py -f `catkin_find --share osrf_gear`/config/qual1a.yaml ~/catkin_ws/src/ariac_qual_1/config/qual_1_conf.yaml```
that is, not ' but `

**Comment by cdrwolfe** [comment]
Cheers, 

This should be fixed now.
